name: clang-format Check
on: 
  push:
    branches:
      - master
  pull_request:
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1
    - name: Run clang-format style check for C/C++/Protobuf programs.
      uses: jidicula/clang-format-action@v4.13.0
      with:
        clang-format-version: '18'
        check-path: 'src'
        exclude-regex: 'incbin|Pyrrhic|test'
      run: |
          clang-format-18 --version
