name: Cross-platform Check

# Test that we get a deterministic 'bench' result across a variety of compilers and platforms. We try to use a older 
# compiler here, to ensure we maintain a reasonable level of compatibility, and make it easy for people to build 
# Halogen

on: 
  push:
    branches:
      - master
  pull_request:

jobs:
  Ubuntu:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        compiler: [g++-10, clang++-13]
        # runners only seem to support up to avx2-pext
        target: [legacy, sse4, avx, avx2, avx2-pext]

    steps:
      - uses: actions/checkout@v4.1.1
        # we need to make sure we checkout the head commit, rather than the merge commit the github actions pipeline generates for us.
        # This ensures we can extract the expected bench from the commit message.
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Create build
        run: |
         cd src
         make ${{ matrix.target }} CXX=${{ matrix.compiler }} EXE=../bin/Halogen -j4

      - name: Check bench matches commit message
        run: |
          cd bin
          commit_bench=$(git show --summary | grep -o "Bench: [0-9]*" | awk '{ print $NF }')
          actual_bench=$(./Halogen bench | tail -1 | grep -o "^[0-9]*")
          if [[ "$actual_bench" != "$commit_bench" ]]; then echo "Incorrect bench, got '$actual_bench' expected '$commit_bench'" && exit 1; else echo "Got correct bench $actual_bench"; fi
          

  Windows:
    runs-on: windows-2022

    strategy:
      matrix:
        config: 
          - { system: mingw64, package: x86_64-gcc, compiler: g++ }
          - { system: clang64, package: clang-x86_64-clang, compiler: clang++ }
        # runners only seem to support up to avx2-pext
        target: [legacy, sse4, avx, avx2, avx2-pext]

    steps:
      - uses: actions/checkout@v4.1.1
        # we need to make sure we checkout the head commit, rather than the merge commit the github actions pipeline generates for us.
        # This ensures we can extract the expected bench from the commit message.
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: msys2/setup-msys2@v2.22.0
        with:
          msystem: ${{matrix.config.system}}
          install: mingw-w64-${{matrix.config.package}} make git

      - name: Add compiler to $PATH env
        shell: bash
        run: echo "PATH=$PATH:/c/msys64/${{ matrix.config.system }}/bin" >> $GITHUB_ENV

      - name: Create build
        shell: msys2 {0}
        run: |
         cd src
         make ${{ matrix.target }} CXX=${{ matrix.config.compiler }} EXE=../bin/Halogen.exe -j4

      - name: Check bench matches commit message
        shell: msys2 {0}
        run: |
          cd bin
          commit_bench=$(git show --summary | grep -o "Bench: [0-9]*" | awk '{ print $NF }')
          actual_bench=$(./Halogen bench | tail -1 | grep -o "^[0-9]*")
          if [[ "$actual_bench" != "$commit_bench" ]]; then echo "Incorrect bench, got '$actual_bench' expected '$commit_bench'" && exit 1; else echo "Got correct bench $actual_bench"; fi

  PGO:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        # TODO: clang PGO builds require different compiler flags, and also appear to produce slower compiles
        compiler: [g++-10]

    steps:
      - uses: actions/checkout@v4.1.1

      - name: Create PGO compiles
        run: |
         cd src
         make pgo CXX=${{ matrix.compiler }} EXE=../bin/Halogen -j4
         
      - name: Run bench
        run: |
         cd bin
         ./Halogen bench