name: FastChess

# This workflow will play games with a debug enabled Halogen

on: 
  push:
    branches:
      - master
  pull_request:

jobs:
  FastChess:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: [sanitize-address, sanitize-undefined, sanitize-thread]

    steps:
      - name: Checkout Halogen repo 
        uses: actions/checkout@v4.1.1
        with:
          path: Halogen

      - name: Build
        working-directory: Halogen/src
        run: make ${{ matrix.target }} EXE=../bin/Halogen -j

      - name: Checkout fast-chess repo
        uses: actions/checkout@v4.1.1
        with:
          repository: Disservin/fast-chess
          path: fast-chess
          ref: d54af1910d5479c669dc731f1f54f9108a251951

      - name: fast-chess build
        working-directory: fast-chess
        run: make -j

      - name: Run games (Blitz)
        working-directory: fast-chess
        run: |
          ./fast-chess -rounds 1 -openings file=app/tests/data/openings.epd format=epd order=random -srand $RANDOM\
               -engine name=halogen1 cmd='TSAN_OPTIONS="suppressions=../Halogen/src/test/tsan.supp" ../Halogen/bin/Halogen'\
               -engine name=halogen2 cmd='TSAN_OPTIONS="suppressions=../Halogen/src/test/tsan.supp" ../Halogen/bin/Halogen'\
               -ratinginterval 1 -report penta=true -each proto=uci tc=4+0.04 option.Threads=4 -log file=fast.log | tee fast.out
          cat fast.log
          ! grep "Assertion" fast.log > /dev/null
          ! grep "disconnect" fast.out > /dev/null

      # no opening for this one to test 'position startpos moves ...'
      - name: Run games (Cyclical)
        working-directory: fast-chess
        run: |
          ./fast-chess -rounds 1 -openings\
               -engine name=halogen1 cmd=../Halogen/bin/Halogen\
               -engine name=halogen2 cmd=../Halogen/bin/Halogen\
               -ratinginterval 1 -report penta=true -each proto=uci tc=40/4 option.Threads=4 -log file=fast.log | tee fast.out
          cat fast.log
          ! grep "Assertion" fast.log > /dev/null
          ! grep "disconnect" fast.out > /dev/null

      - name: Run games (FRC)
        working-directory: fast-chess
        run: |
          echo "bqnb1rkr/pp3ppp/3ppn2/2p5/5P2/P2P4/NPP1P1PP/BQ1BNRKR w KQkq - 2 9" > opening.epd
          ./fast-chess -variant fischerandom -rounds 1 -openings file=opening.epd format=epd order=random -srand $RANDOM\
               -engine name=halogen1 cmd=../Halogen/bin/Halogen\
               -engine name=halogen2 cmd=../Halogen/bin/Halogen\
               -ratinginterval 1 -report penta=true -each proto=uci tc=40/4 option.Threads=4 -log file=fast.log | tee fast.out
          cat fast.log
          ! grep "Assertion" fast.log > /dev/null
          ! grep "disconnect" fast.out > /dev/null

      - name: Other UCI commands
        working-directory: Halogen
        run: |
          ./bin/Halogen "setoption name MultiPV value 8" "setoption name Threads value 4" "position fen 1r4k1/8/5PP1/K7/6NR/7B/1r6/7R w - - 0 1" "go movetime 5000"
          ./bin/Halogen "setoption name MultiPV value 8" "setoption name Threads value 4" "position fen 1r4k1/8/5PP1/K7/6NR/7B/1r6/7R w - - 0 1" "go mate 3"
          ./bin/Halogen "setoption name MultiPV value 8" "setoption name Threads value 4" "position fen 1r4k1/8/5PP1/K7/6NR/7B/1r6/7R w - - 0 1" "go nodes 100000"
          ./bin/Halogen "setoption name MultiPV value 8" "setoption name Threads value 4" "position fen 1r4k1/8/5PP1/K7/6NR/7B/1r6/7R w - - 0 1" "go depth 10"