# This workflow will run matetrack on the PR

name: Matetrack

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  Matetrack:
    name: Matetrack
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Halogen repo 
        uses: actions/checkout@v4.1.1
        with:
          path: Halogen
          lfs: true

      - name: Build Halogen
        working-directory: Halogen/src
        run: make -j

      - name: Checkout matetrack repo
        uses: actions/checkout@v4
        with:
          repository: KierenP/matetrack
          path: matetrack
          ref: be0f7843b2b174609598a9a5dd65104b7354b622

      - name: matetrack install deps
        working-directory: matetrack
        run: pip install -r requirements.txt

      - name: Run matetrack
        working-directory: matetrack
        run: |
          python matecheck.py --engine $GITHUB_WORKSPACE/Halogen/bin/Halogen-pgo --epdFile mates2000.epd --nodes 100000 | tee matecheckout.out
          ! grep "issues were detected" matecheckout.out > /dev/null
