name: Openbench

# Test that we get a deterministic 'bench' result across a variety of compilers and platforms. We try to use a older 
# compiler here, to ensure we maintain a reasonable level of compatibility, and make it easy for people to build 
# Halogen

on: 
  push:
    branches:
      - master
  pull_request:

jobs:
  gcc-PGO:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        compiler: [g++-11]

    steps:
      - uses: actions/checkout@v4.1.1

      - name: Install
        run: |
          sudo apt update
          sudo apt install ${{ matrix.compiler }}

      - name: Create PGO compiles
        run: |
          cd src
          make CXX=${{ matrix.compiler }} EXE=../bin/Halogen -j4
         
      - name: Run bench
        run: |
          cd bin
          ./Halogen bench

  clang-PGO:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        compiler: [clang++-12]
        llvm: [llvm-12]
        profdata: [llvm-profdata-12]

    steps:
      - uses: actions/checkout@v4.1.1

      - name: Install
        run: |
          sudo apt update
          sudo apt install ${{ matrix.llvm }} ${{ matrix.compiler }}

      - name: Create PGO compiles
        run: |
          cd src
          make CXX=${{ matrix.compiler }} LLVM_PROFDATA=${{ matrix.profdata }} EXE=../bin/Halogen -j4
         
      - name: Run bench
        run: |
          cd bin
          ./Halogen bench
