name: Openbench

# Test that we get a deterministic 'bench' result across a variety of compilers and platforms. We try to use a older 
# compiler here, to ensure we maintain a reasonable level of compatibility, and make it easy for people to build 
# Halogen

on: 
  push:
    branches:
      - master
  pull_request:

jobs:
  gcc-PGO:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        compiler: [g++-11]

    steps:
      - uses: actions/checkout@v4.1.1

      - name: Install
        run: |
          sudo apt update
          sudo apt install ${{ matrix.compiler }}

      - name: Create PGO compiles
        run: |
          cd src
          make CXX=${{ matrix.compiler }} EXE=../bin/Halogen -j4
         
      - name: Run bench
        run: |
          cd bin
          ./Halogen bench

  clang-PGO:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        config:
          - { compiler: clang++-12, packages: "clang-12 llvm-12", profdata: llvm-profdata-12 }

    steps:
      - uses: actions/checkout@v4.1.1

      - name: Install
        run: |
          sudo apt update
          sudo apt install ${{ matrix.config.packages }}

      - name: Create PGO compiles
        run: |
          cd src
          make CXX=${{ matrix.config.compiler }} LLVM_PROFDATA=${{ matrix.config.profdata }} EXE=../bin/Halogen -j4
         
      - name: Run bench
        run: |
          cd bin
          ./Halogen bench
