name: Regression Check

# Use a variety of sanitizers with the latest compilers to detect data races and undefined behaviour

on: 
  push:
    branches:
      - master
  pull_request:

jobs:
  Sanitizer:
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        compiler: [g++-14, clang++-18]
        target: [sanitize-address, sanitize-undefined, sanitize-thread]

    steps:
      - uses: actions/checkout@v4.1.1

      - name: Create sanitizer builds
        run: |
          cd src
          make ${{ matrix.target }} CXX=${{ matrix.compiler }} EXE=../bin/Halogen -j2
          
      - name: Run
        run: |
          cd bin
          ./Halogen <<EOF
            setoption name Threads value 2
            setoption name MultiPV value 8
            ucinewgame
            position fen r1bq1rk1/1p1nppbp/3p1np1/p1p5/2PP4/2N1PN2/PPQ1BPPP/R1B2RK1 w - - 0 1
            go wtime 4810 btime 4810 winc 500 binc 500
            position fen r1bq1rk1/1p1nppbp/3p1np1/p1p5/2PP4/2N1PN2/PPQ1BPPP/R1B2RK1 w - - 0 1 moves h2h3
            go wtime 4710 btime 4810 winc 500 binc 500
            setoption name UCI_Chess960 value true
            position fen nbnrbkrq/pppppppp/8/8/8/8/PPPPPPPP/NBNRBKRQ w DGdg - 0 1 moves d2d3 a7a6 e1d2 b7b6 c1b3 c7c6 f1d1
            go movetime 10000
            position fen 8/2p4P/8/kr6/6R1/8/8/1K6 w - - 0 1
            go movetime 10000
          EOF
