name: Windows (Clang64)

on: 
  push:
    branches:
      - master
  pull_request:

jobs:
  Windows:
    runs-on: windows-latest

    strategy:
      matrix:
        config:
          - { system: clang64, package: clang-x86_64-clang, compiler: clang++ }
          - { system: mingw64, package: x86_64-gcc, compiler: g++ }
        # runners only seem to support up to avx2-pext
        target: [pgo]

    steps:
      - uses: actions/checkout@v4.1.1
        # we need to make sure we checkout the head commit, rather than the merge commit the github actions pipeline generates for us.
        # This ensures we can extract the expected bench from the commit message.
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: msys2/setup-msys2@v2.22.0
        with:
          msystem: ${{matrix.config.system}}
          install: mingw-w64-${{matrix.config.package}} make git mingw-w64-x86_64-git-lfs

      - name: Add compiler to $PATH env
        shell: bash
        run: echo "PATH=$PATH:/c/msys64/${{ matrix.config.system }}/bin" >> $GITHUB_ENV

      - name: Create build
        shell: msys2 {0}
        working-directory: src
        run: make ${{ matrix.target }} CXX=${{ matrix.config.compiler }} EXE=../bin/Halogen.exe -j

      - name: Check bench matches commit message
        shell: msys2 {0}
        run: |
          cd bin
          commit_bench=$(git show --summary | grep -o "Bench: [0-9]*" | awk '{ print $NF }')
          actual_bench=$(./Halogen bench | tail -1 | grep -o "^[0-9]*")
          if [[ "$actual_bench" != "$commit_bench" ]]; then echo "Incorrect bench, got '$actual_bench' expected '$commit_bench'" && exit 1; else echo "Got correct bench $actual_bench"; fi
